"use client";
import { useState, useTransition } from "react";
import type { AdminBetaData } from "@/lib/admin-beta";
import { adminTestPush } from "@/app/actions/admin-push";
export function AdminBetaAnalytics({ data }: { data: AdminBetaData }) {
  const [days, setDays] = useState(7);
  const [busy, start] = useTransition();
  const [message, setMessage] = useState("");
  const report = data.periods.find(period => period.days === days)!;
  const fraction = (n: number, total: number) => total ? `${Math.round(n / total * 100)}% · ${n}/${total}` : "No eligible accounts yet";
  return <section className="admin-beta" aria-labelledby="beta-heading">
    <header className="admin-beta-header"><div><h2 id="beta-heading">Beta usage</h2><p>Are people getting started, finding value, and coming back?</p></div><label>Period <select value={days} onChange={event => setDays(Number(event.target.value))}><option value={7}>Last 7 days</option><option value={28}>Last 28 days</option></select></label></header>
    <div className="admin-beta-grid">
      {[[report.today, "Active today (UTC)"], [report.active, `Active in ${days} days`], [report.returning, "Also active in previous period"], [report.newUsers, "New accounts"], [fraction(report.onboarded, report.newUsers), "New accounts onboarded"], [fraction(report.activated, report.newUsers), "New accounts taking a core action"], [fraction(report.invites.accepted, report.invites.sent), "Invites accepted to date"], [fraction(report.retention.returned, report.retention.eligible), "Returned in signup week 2"]].map(([value, label]) => <article className="admin-beta-metric" key={String(label)}><strong>{value}</strong><span>{label}</span></article>)}
    </div>
    <p className="admin-beta-note">Admins, the review account, and configured test accounts are excluded. Active means a recorded app visit or feature action, not a login. A core action is saving a class, following a calendar, publishing a class, joining/creating a group, exporting a share image, or event registration. Activation is measured to date; new accounts may still be getting started.</p>
    <p className="admin-beta-note">Daily app, screen and class-detail signals {report.firstObserved ? `have been observed since ${report.firstObserved}` : "start with this release"}. Earlier visits cannot be reconstructed. Week 2 measures activity on signup days 7–13 for accounts with 14 full days of observation; it will remain empty until those cohorts mature. Web and native use are combined.</p>
    <details open><summary>Feature adoption</summary><div className="admin-beta-table"><table><thead><tr><th>Feature</th><th>Accounts</th><th>Actions / account-days</th></tr></thead><tbody>{report.features.map(row => <tr key={row.label}><td>{row.label}</td><td>{row.users}</td><td>{row.events}{row.dailySignal ? " account-days" : " actions"}</td></tr>)}</tbody></table></div><p className="admin-beta-note">Visits and screen errors count distinct account-days, not every open or every failure. Feature actions count recorded events; repeated requests can count more than once. Error signals are a lower bound when the network or server is unavailable.</p></details>
    <details><summary>Daily usage and saves</summary><div className="admin-beta-table"><table><thead><tr><th>Date (UTC)</th><th>Active accounts</th><th>Save actions</th></tr></thead><tbody>{report.daily.map(day => <tr key={day.date}><td>{day.date}</td><td>{day.active}</td><td>{day.saves}</td></tr>)}</tbody></table></div><p className="admin-beta-note">Previous period: {report.previousActive} active accounts. Daily rows use calendar days; summary periods use rolling {days}-day windows.</p></details>
    <details><summary>Signup sources</summary>{report.sources.length ? <ul>{report.sources.map(source => <li key={source.source}>{source.source}: {source.count}</li>)}</ul> : <p>No new accounts in this period.</p>}</details>
    <details><summary>Accounts that may need help ({report.stuck.length}{report.stuck.length === 20 ? "+" : ""})</summary>{report.stuck.length ? <ul>{report.stuck.map(person => <li key={person.id}><strong>{person.name}</strong> · {person.email}<br />{person.reason}</li>)}</ul> : <p>No accounts meet the follow-up criteria.</p>}<p className="admin-beta-note">This is a follow-up cue, not proof of a bug. Limited to 20 recent accounts; no messages are sent automatically.</p></details>
    <details><summary>Android push health</summary><p>Firebase credentials: <strong>{data.androidPush.configured ? "Present" : "Missing"}</strong> · {data.androidPush.devices} unexpired Android registrations</p>{data.androidPush.missing.length > 0 && <p>Setup needed: {data.androidPush.missing.join(", ")}</p>}<button className="adminback" disabled={busy || !data.androidPush.configured} onClick={() => start(async () => {try {setMessage((await adminTestPush("android")).message);} catch {setMessage("Couldn’t queue the push test. Try again.");}})}>Send test to my Android</button><p className="admin-beta-note">The shared delivery queue appears below. Credentials and queue acceptance do not prove delivery.</p></details>
    <details><summary>iPhone push health</summary><p>Apple credentials: <strong>{data.push.configured ? "Present" : "Missing"}</strong> · TestFlight environment: <strong>{data.push.production ? "Production" : "Incorrect: sandbox"}</strong></p>{data.push.missing.length > 0 && <p>Setup needed: {data.push.missing.join(", ")}</p>}<p>{data.push.devices} unexpired registrations · {data.push.queued} queued notifications · {data.push.retrying} attempted notifications still queued</p>{data.push.oldest && <p>Oldest queued: {data.push.oldest}</p>}<p className="admin-beta-note">Includes admin devices. Present credentials and a registered device do not prove Apple delivery. Check after refresh for queue changes.</p><button className="adminback" disabled={busy || !data.push.configured || !data.push.production} onClick={() => start(async () => { try { const result = await adminTestPush(); setMessage(result.message); } catch { setMessage("Couldn’t queue the push test. Try again."); } })}>{busy ? "Queuing…" : "Send test to my iPhone"}</button>{message && <p role="status">{message}</p>}</details>
  </section>;
}
