"use client";

import { useEffect, useMemo, useRef, useState, useTransition, type ReactNode } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { Icon } from "@/components/Icon";
import type { DirPerson, DirStudio } from "@/components/DirectoryRows";
import { FavoritePersonButton } from "@/components/FavoritePersonButton";
import { FavoritePlaceButton } from "@/components/FavoritePlaceButton";
import type { BrowseDay } from "@/app/actions/discover";
import { Toast, useToast } from "@/components/Toast";
import { CreateGroupSheet } from "@/components/SavedScreen";
import { discoverGroups, discoverPeople, discoverStudios } from "@/app/actions/discover";
import { CalendarList, type WeekDayRows } from "@/components/WeekView";
import { ClassOpener } from "@/components/ClassOpener";
import { setGoing } from "@/app/actions/going";
import { addGroupClasses, managedGroupDestinations, type GroupDestination } from "@/app/actions/groups";
import { PLACE_KIND_LABELS, PLACE_KINDS } from "@/lib/studio";

export type DiscoverHalf = "people" | "places" | "classes" | "groups";
type Group = { id:string; name:string; slug:string; description:string|null; purpose:string; lat:number|null; lng:number|null };
type UpcomingItem = BrowseDay["items"][number] & { day:string };
const distanceOptions = [["1","Within 1 mile"],["5","Within 5 miles"],["10","Within 10 miles"],["25","Within 25 miles"]] as const;

export function DiscoverList({ people,studios=[],cities,myLat=null,myLng=null,startHalf,upcoming=[],groups=[],backHref,hideBack=false }: { people:DirPerson[];studios?:DirStudio[];cities:string[];myCity?:string|null;myLat?:number|null;myLng?:number|null;startHalf?:DiscoverHalf;upcoming?:BrowseDay[];groups?:Group[];backHref:string;hideBack?:boolean }) {
  const router=useRouter();
  const [saved,setSaved]=useState<Record<string,boolean>>(()=>Object.fromEntries(upcoming.flatMap((day)=>day.items.map((item)=>[`${item.classId}|${item.iso}`,item.saved]))));
  const [savedSheet,setSavedSheet]=useState<UpcomingItem|null>(null);
  const [saveGroups,setSaveGroups]=useState<GroupDestination[]>([]);
  const [groupSaved,setGroupSaved]=useState<Record<string,boolean>>({});
  const [savePending,startSave]=useTransition();
  const [groupCreateOpen,setGroupCreateOpen]=useState(false);
  const [toastMsg,toastOn,toast]=useToast();
  const [tab,setTab]=useState<DiscoverHalf>(startHalf??"people");
  const [filtersOpen,setFiltersOpen]=useState(false);
  const [studioRows,setStudioRows]=useState(studios);
  const [groupRows,setGroupRows]=useState(groups);
  const [peopleRows,setPeopleRows]=useState(people);
  const [directoryPending,startDirectory]=useTransition();
  const loadedDirectories=useRef(new Set<DiscoverHalf>());
  const [searchOpen,setSearchOpen]=useState(false); const [query,setQuery]=useState("");
  const [classType,setClassType]=useState(""); const [distance,setDistance]=useState("");
  const [discipline,setDiscipline]=useState(""); const [peopleDistance,setPeopleDistance]=useState("");
  const [placeKind,setPlaceKind]=useState(""); const [studioType,setStudioType]=useState(""); const [studioDistance,setStudioDistance]=useState("");
  const [purpose,setPurpose]=useState(""); const [groupDistance,setGroupDistance]=useState(""); const [groupSort,setGroupSort]=useState("");
  const activeFilters=tab==="classes"?Number(!!classType)+Number(!!distance):tab==="people"?Number(!!discipline)+Number(!!peopleDistance):tab==="places"?Number(!!placeKind)+Number(!!studioType)+Number(!!studioDistance):Number(!!purpose)+Number(!!groupDistance)+Number(!!groupSort);
  const clearFilters=()=>{if(tab==="classes"){setClassType("");setDistance("");}else if(tab==="people"){setDiscipline("");setPeopleDistance("");}else if(tab==="places"){setPlaceKind("");setStudioType("");setStudioDistance("");}else{setPurpose("");setGroupDistance("");setGroupSort("");}};
  const q=query.trim().toLowerCase();
  const allUpcoming=useMemo(()=>upcoming.flatMap((day)=>day.items.map((item)=>({...item,day:day.label}))).filter((item)=>!q||[item.name,item.where,item.attributionName].some((value)=>(value??"").toLowerCase().includes(q))),[upcoming,q]);
  const classTypes=[...new Set(allUpcoming.map((item)=>item.classType).filter((value):value is string=>!!value))].sort();
  const filteredUpcoming=allUpcoming.filter((item)=>{if(classType&&item.classType!==classType)return false;if(distance){if(myLat==null||myLng==null||item.lat==null||item.lng==null)return false;if(milesBetween(myLat,myLng,item.lat,item.lng)>Number(distance))return false;}return true;});
  const filteredUpcomingDays=upcoming.map((day)=>({iso:day.iso,label:day.label,items:filteredUpcoming.filter((item)=>item.iso===day.iso)})).filter((day)=>day.items.length>0);
  const disciplines=[...new Set(peopleRows.flatMap((person)=>person.disciplines))].sort();
  const shownPeople=peopleRows.filter((person)=>person.kind==="coach"&&(!q||[person.name,person.title,person.location,person.handle,...person.disciplines].some((value)=>value.toLowerCase().includes(q)))&&(!discipline||person.disciplines.includes(discipline))&&(!peopleDistance||(myLat!=null&&myLng!=null&&person.lat!=null&&person.lng!=null&&milesBetween(myLat,myLng,person.lat,person.lng)<=Number(peopleDistance))));
  const studioTypes=[...new Set(studioRows.flatMap((studio)=>studio.types))].sort();
  const shownStudios=studioRows.filter((studio)=>(!q||[studio.name,studio.address,...studio.types].some((value)=>value.toLowerCase().includes(q)))&&(!placeKind||studio.placeKind===placeKind)&&(!studioType||studio.types.includes(studioType))&&(!studioDistance||(myLat!=null&&myLng!=null&&studio.lat!=null&&studio.lng!=null&&milesBetween(myLat,myLng,studio.lat,studio.lng)<=Number(studioDistance))));
  const shownGroups=groupRows.filter((group)=>(!q||`${group.name} ${group.description??""}`.toLowerCase().includes(q))&&(!purpose||group.purpose===purpose)&&(!groupDistance||(myLat!=null&&myLng!=null&&group.lat!=null&&group.lng!=null&&milesBetween(myLat,myLng,group.lat,group.lng)<=Number(groupDistance)))).sort((a,b)=>groupSort==="name"?a.name.localeCompare(b.name):0);
  const activityByName=upcoming.flatMap((day)=>day.items).reduce((counts,item)=>{const key=item.attributionName.trim().toLowerCase();if(key)counts.set(key,(counts.get(key)??0)+1);return counts;},new Map<string,number>());
  const showSavedConfirmation=async(item:UpcomingItem)=>{setSaveGroups(await managedGroupDestinations());setGroupSaved({});setSavedSheet(item);};
  const openSavedConfirmation=(item:UpcomingItem)=>startSave(()=>showSavedConfirmation(item));
  const saveClass=(item:UpcomingItem)=>startSave(async()=>{const key=`${item.classId}|${item.iso}`;if(saved[key]){await showSavedConfirmation(item);return;}const result=await setGoing(item.classId,item.iso,true);if(!result.ok)return toast(result.error??"Couldn't save that class");setSaved((current)=>({...current,[key]:true}));await showSavedConfirmation(item);router.refresh();});
  const unsaveClass=(item:UpcomingItem)=>startSave(async()=>{const result=await setGoing(item.classId,item.iso,false);if(!result.ok)return toast(result.error??"Couldn't remove that class");setSaved((current)=>({...current,[`${item.classId}|${item.iso}`]:false}));setSavedSheet(null);toast(`${item.name} was removed from your calendar`);router.refresh();});
  const saveToGroup=(item:UpcomingItem,group:GroupDestination)=>startSave(async()=>{const result=await addGroupClasses(group.slug,[{classId:item.classId,iso:item.iso}]);if(!result.ok)return toast(result.error);setGroupSaved((current)=>({...current,[group.id]:true}));toast(`${item.name} was added to ${group.name}`);});
  const discoverCalendarDays:WeekDayRows[]=filteredUpcomingDays.map((day)=>({iso:day.iso,label:day.label,rows:day.items.map((item)=>{const isSaved=!!saved[`${item.classId}|${item.iso}`];const base=item.base.replace(/^\//,"");return {key:`${item.classId}.${item.iso}`,name:item.name,where:item.where||"Location to come",hm:item.hm,ap:item.ap,coach:{id:item.classId,name:item.attributionName,color:item.coachColor,photo:item.coachPhoto},href:`/${base}/${item.classId}?d=${item.iso}&from=discover-classes`,classId:item.classId,iso:item.iso,base,corner:item.own?undefined:<button type="button" aria-label={isSaved?`Manage saved class ${item.name}`:`Save ${item.name} to your calendar`} className={`calendar-save-action calendar-overlay-save${isSaved?" saved":""}`} disabled={savePending} onClick={()=>isSaved?openSavedConfirmation(item):saveClass(item)}><Icon name={isSaved?"bookmark_added":"bookmark"} size={17}/>{isSaved?"Saved":"Save"}</button>};})}));
  useEffect(()=>{
    if(loadedDirectories.current.has(tab))return;
    if(tab==="places"){loadedDirectories.current.add(tab);startDirectory(async()=>setStudioRows(await discoverStudios()));}
    if(tab==="groups"){loadedDirectories.current.add(tab);startDirectory(async()=>setGroupRows(await discoverGroups()));}
    if(tab==="people"){loadedDirectories.current.add(tab);startDirectory(async()=>{const data=await discoverPeople();setPeopleRows(data.people);});}
  },[tab,studioRows.length,groupRows.length,peopleRows.length]);
  return <>
    <div className="discover-title-row"><h1>Near you</h1><button type="button" aria-label="Search near you" aria-expanded={searchOpen} onClick={()=>setSearchOpen((open)=>!open)}><Icon name="search" size={24}/></button></div>
    {searchOpen&&<div className="dissearchrow discover-searchrow"><label className="dissearch"><Icon name="search" size={20} className="dissearch-ic"/><input autoFocus className="dissearch-in" type="search" value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="Search FittList" aria-label="Search FittList"/>{query&&<button type="button" className="dissearch-x" onClick={()=>setQuery("")} aria-label="Clear search"><Icon name="close" size={19}/></button>}</label></div>}
    <div className="discover-directory-tabs" role="tablist">{([['people','People'],['places','Studios'],['groups','Groups']] as const).map(([value,label])=><button role="tab" aria-selected={tab===value} className={tab===value?"on":""} onClick={()=>setTab(value)} key={value}>{label}</button>)}</div>
    {tab==="classes"&&<><FilterRow active={activeFilters} onOpen={()=>setFiltersOpen(true)}><Filter label="Distance" value={distance} onChange={setDistance} all="Any distance" options={distanceOptions} disabled={myLat==null||myLng==null}/><Filter label="Type" value={classType} onChange={setClassType} all="Any type" options={classTypes}/></FilterRow>{discoverCalendarDays.length?<ClassOpener handle=""><CalendarList className="discover-calendar-list" days={discoverCalendarDays}/></ClassOpener>:<Empty>There are no classes matching these filters.</Empty>}</>}
    {tab==="people"&&<><FilterRow active={activeFilters} onOpen={()=>setFiltersOpen(true)}><Filter label="Distance" value={peopleDistance} onChange={setPeopleDistance} all="Any distance" options={distanceOptions} disabled={myLat==null||myLng==null}/><Filter label="Specialty" value={discipline} onChange={setDiscipline} all="Any specialty" options={disciplines}/></FilterRow>{directoryPending?<Empty>Loading people…</Empty>:shownPeople.length?<div className="discover-person-grid">{shownPeople.map((person,index)=><DiscoverPerson person={person} index={index} activity={activityByName.get(person.name.trim().toLowerCase())??person.classesThisWeek} key={person.id}/>)}</div>:<Empty>There are no people matching these filters.</Empty>}</>}
    {tab==="places"&&<><FilterRow active={activeFilters} onOpen={()=>setFiltersOpen(true)}><Filter label="Distance" value={studioDistance} onChange={setStudioDistance} all="Any distance" options={distanceOptions} disabled={myLat==null||myLng==null}/><Filter label="Type" value={placeKind} onChange={setPlaceKind} all="Any type" options={PLACE_KINDS.map((kind)=>[kind,PLACE_KIND_LABELS[kind]] as const)}/><Filter label="Category" value={studioType} onChange={setStudioType} all="Any category" options={studioTypes}/></FilterRow>{directoryPending?<Empty>Loading studios…</Empty>:shownStudios.length?<StudioGrid studios={shownStudios}/>:<Empty>There are no studios matching these filters.</Empty>}</>}
    {tab==="groups"&&<><FilterRow active={activeFilters} onOpen={()=>setFiltersOpen(true)}><Filter label="Distance" value={groupDistance} onChange={setGroupDistance} all="Any distance" options={distanceOptions} disabled={myLat==null||myLng==null}/><Filter label="Purpose" value={purpose} onChange={setPurpose} all="Any purpose" options={[["plan","Plan together"],["community","Community"],["event","Events"]]}/><Filter label="Sort" value={groupSort} onChange={setGroupSort} all="Newest" options={[["name","Name"]]}/></FilterRow>{directoryPending?<Empty>Loading groups…</Empty>:shownGroups.length?<GroupGrid groups={shownGroups}/>:groupRows.length?<Empty>There are no groups matching these filters.</Empty>:<div className="discover-groups-empty"><span><Icon name="groups" size={32}/></span><h2>Plan fitness together</h2><p>Groups are shared calendars and updates for the people you train with. Add classes, invite members, and keep everyone&rsquo;s plans in one place.</p><button type="button" className="btn si" onClick={()=>setGroupCreateOpen(true)}><Icon name="add" size={21}/>Create a group</button></div>}</>}
    {!hideBack&&<Link className="logoutbtn" href={backHref}>Back to your week</Link>}
    <Toast msg={toastMsg} on={toastOn}/>
    {savedSheet&&<SavedClassConfirmation item={savedSheet} groups={saveGroups} groupSaved={groupSaved} pending={savePending} onClose={()=>setSavedSheet(null)} onUnsave={()=>unsaveClass(savedSheet)} onGroup={(group)=>saveToGroup(savedSheet,group)}/>}
    {filtersOpen&&<div className="sheet-scrim" onClick={(event)=>{if(event.target===event.currentTarget)setFiltersOpen(false);}}><div className="sheet discover-filters-sheet"><button type="button" className="iconbtn sheetclose" aria-label="Close" onClick={()=>setFiltersOpen(false)}><Icon name="close" size={18}/></button><div className="discover-filters-sheet-head"><h2>Filters</h2><button type="button" disabled={!activeFilters} onClick={clearFilters}>Clear all</button></div><div className="discover-filters-sheet-fields">{tab==="classes"?<><Filter label="Distance" value={distance} onChange={setDistance} all="Any distance" options={distanceOptions} disabled={myLat==null||myLng==null}/><Filter label="Type" value={classType} onChange={setClassType} all="Any type" options={classTypes}/></>:tab==="people"?<><Filter label="Distance" value={peopleDistance} onChange={setPeopleDistance} all="Any distance" options={distanceOptions} disabled={myLat==null||myLng==null}/><Filter label="Specialty" value={discipline} onChange={setDiscipline} all="Any specialty" options={disciplines}/></>:tab==="places"?<><Filter label="Distance" value={studioDistance} onChange={setStudioDistance} all="Any distance" options={distanceOptions} disabled={myLat==null||myLng==null}/><Filter label="Type" value={placeKind} onChange={setPlaceKind} all="Any type" options={PLACE_KINDS.map((kind)=>[kind,PLACE_KIND_LABELS[kind]] as const)}/><Filter label="Category" value={studioType} onChange={setStudioType} all="Any category" options={studioTypes}/></>:<><Filter label="Distance" value={groupDistance} onChange={setGroupDistance} all="Any distance" options={distanceOptions} disabled={myLat==null||myLng==null}/><Filter label="Purpose" value={purpose} onChange={setPurpose} all="Any purpose" options={[["plan","Plan together"],["community","Community"],["event","Events"]]}/><Filter label="Sort" value={groupSort} onChange={setGroupSort} all="Newest" options={[["name","Name"]]}/></>}</div><button type="button" className="btn discover-filters-done" onClick={()=>setFiltersOpen(false)}>Show results</button></div></div>}
    {groupCreateOpen&&<CreateGroupSheet onClose={()=>setGroupCreateOpen(false)}/>}
  </>;
}

function FilterRow({children,active,onOpen}:{children:ReactNode;active:number;onOpen:()=>void}){return <div className="discover-class-filters discover-tab-filters"><button type="button" className={`discover-filters-pill${active?" on":""}`} aria-label="Filters" onClick={onOpen}><Icon name="tune" size={20}/>{active>0&&<span className="discover-filters-count">{active}</span>}</button>{children}</div>}
function Filter({label,value,onChange,all,options,disabled=false}:{label:string;value:string;onChange:(value:string)=>void;all:string;options:readonly (string|readonly[string,string])[];disabled?:boolean}){return <label><select aria-label={label} value={value} onChange={(event)=>onChange(event.target.value)} disabled={disabled}><option value="">{all}</option>{options.map((option)=>{const [value,label]=typeof option==="string"?[option,option]:option;return <option value={value} key={value}>{label}</option>})}</select></label>}
function Empty({children}:{children:ReactNode}){return <p className="discover-tab-empty">{children}</p>}
function milesBetween(lat1:number,lng1:number,lat2:number,lng2:number){const radians=(degrees:number)=>degrees*Math.PI/180;const dLat=radians(lat2-lat1);const dLng=radians(lng2-lng1);const a=Math.sin(dLat/2)**2+Math.cos(radians(lat1))*Math.cos(radians(lat2))*Math.sin(dLng/2)**2;return 3958.8*2*Math.atan2(Math.sqrt(a),Math.sqrt(1-a));}
function DiscoverPerson({person,index,activity}:{person:DirPerson;index:number;activity:number}){return <div className="discover-person-tile"><Link href={`/${person.handle}?from=discover-people`} className="discover-person-main"><span className="discover-person-face" style={{background:person.color}}>{person.photo?<img src={person.photo} alt="" loading={index<4?"eager":"lazy"} decoding="async"/>:person.name.trim().charAt(0).toUpperCase()}</span><span className="discover-person-copy"><strong>{person.name}</strong><small className="discover-person-location">{[activity?`${activity} this week`:person.title||person.disciplines.slice(0,2).join(" · "),person.location].filter(Boolean).join(" · ")}</small></span></Link><FavoritePersonButton person={person}/></div>}
function StudioGrid({studios}:{studios:DirStudio[]}){return <div className="discover-studio-grid">{studios.map((studio,index)=><div className="discover-studio-tile" key={studio.id}><Link href={`/s/${studio.slug}?from=discover-studios`}><span className="discover-studio-media">{studio.photo?<img src={studio.photo} alt="" loading={index<4?"eager":"lazy"} decoding="async"/>:<span className="discover-studio-placeholder" style={{background:studio.color}}>{studio.name.trim().charAt(0).toUpperCase()}</span>}</span><strong>{studio.name}</strong><small>{studio.types.slice(0,2).join(" · ")||"Fitness space"}</small></Link><FavoritePlaceButton studio={studio}/></div>)}</div>}
function GroupGrid({groups}:{groups:Group[]}){return <div className="discover-group-grid">{groups.map((group)=><Link className="discover-group-tile" href={`/g/${group.slug}?from=discover-groups`} key={group.id}><span><Icon name="groups" size={28}/></span><strong>{group.name}</strong><small>{group.description||"Open group"}</small></Link>)}</div>}
function SavedClassConfirmation({item,groups,groupSaved,pending,onClose,onUnsave,onGroup}:{item:UpcomingItem;groups:GroupDestination[];groupSaved:Record<string,boolean>;pending:boolean;onClose:()=>void;onUnsave:()=>void;onGroup:(group:GroupDestination)=>void}){return <div className="sheet-scrim" onClick={(event)=>{if(event.target===event.currentTarget&&!pending)onClose();}}><div className="sheet discover-saved-sheet" role="dialog" aria-modal="true" aria-labelledby="discover-saved-title"><button type="button" className="iconbtn sheetclose" aria-label="Close" onClick={onClose}><Icon name="close" size={18}/></button><div className="discover-saved-head"><div><h2 id="discover-saved-title"><Icon name="check" size={17}/>Saved to your calendar</h2><p>{item.name} · {item.hm}{item.ap.toLowerCase()}</p></div><button type="button" disabled={pending} onClick={onUnsave}>Unsave</button></div><div className="discover-saved-groups"><h3>Save to groups</h3>{groups.length?groups.map((group)=>{const on=!!groupSaved[group.id];return <button type="button" disabled={pending||on} onClick={()=>onGroup(group)} key={group.id}><span><Icon name="groups" size={20}/></span><strong>{group.name}</strong><Icon name={on?"check_circle":"add_circle"} size={22}/></button>}):<p>Groups you manage will appear here.</p>}</div></div></div>}
