import type { IconProps } from "@phosphor-icons/react";
import type { ComponentType } from "react";
import { ArrowBendUpLeft, ArrowRight, ArrowSquareOut, ArrowUpRight, At, BatteryFull, Bell, BookmarkSimple, Calendar, CalendarCheck, CalendarDot, CalendarDots, CaretDown, CaretLeft, CaretRight, CaretUp, CellSignalFull, ChatCircle, ChatCircleText, Chats, Check, CheckCircle, Circle, Clock, Compass, Copy, DeviceMobile, DiceFive, DotsThree, Envelope, Export, Eye, Fingerprint, Flag, GearSix, Globe, GlobeHemisphereWest, GridNine, Heart, House, Image, Info, Lightning, Link, List, LockKey, MagnifyingGlass, MapPin, Megaphone, Moon, Palette, PaperPlaneTilt, PencilSimple, Phone, Plus, PlusCircle, Pulse, QrCode, Rows, SealCheck, ShieldCheck, SignOut, SlidersHorizontal, Sparkle, Star, Storefront, Sun, TextT, Trash, User, UserCircle, UserPlus, Users, UsersThree, WifiHigh, X } from "./PhosphorIcons";

const ICONS: Record<string, ComponentType<IconProps>> = {
  add_circle: PlusCircle,
  forum: Chats,
  check_circle: CheckCircle,
  account_circle: UserCircle,
  person: User,
  activity: Pulse,
  add: Plus,
  admin_panel_settings: ShieldCheck,
  alternate_email: At,
  arrow_back: CaretLeft,
  arrow_forward: ArrowRight,
  arrow_outward: ArrowUpRight,
  auto_awesome: Sparkle,
  auto_awesome_outline: Sparkle,
  bolt: Lightning,
  bolt_filled: Lightning,
  bookmark: BookmarkSimple,
  bookmark_added: BookmarkSimple,
  calendar_month: CalendarDots,
  calendar_today: Calendar,
  calendar_view_day: Rows,
  calendar_view_month: GridNine,
  casino: DiceFive,
  format_size: TextT,
  call: Phone,
  campaign: Megaphone,
  chat: ChatCircleText,
  chat_bubble: ChatCircle,
  check: Check,
  chevron_left: CaretLeft,
  chevron_right: CaretRight,
  close: X,
  content_copy: Copy,
  dark_mode: Moon,
  delete: Trash,
  edit: PencilSimple,
  event: CalendarDot,
  event_added: CalendarCheck,
  event_available: CalendarCheck,
  expand_less: CaretUp,
  expand_more: CaretDown,
  favorite: Heart,
  favorite_filled: Heart,
  fingerprint: Fingerprint,
  flag: Flag,
  group: Users,
  explore: Compass,
  star: Star,
  star_filled: Star,
  groups: UsersThree,
  home: House,
  image: Image,
  info: Info,
  ios_share: Export,
  light_mode: Sun,
  link: Link,
  list: List,
  lock: LockKey,
  logout: SignOut,
  mail: Envelope,
  menu: List,
  more_horiz: DotsThree,
  north_east: ArrowUpRight,
  notifications: Bell,
  open_in_new: ArrowSquareOut,
  palette: Palette,
  person_add: UserPlus,
  phone_iphone: DeviceMobile,
  place: MapPin,
  public: Globe,
  public_off: GlobeHemisphereWest,
  qr_code_2: QrCode,
  schedule: Clock,
  signal_cellular_alt: CellSignalFull,
  wifi: WifiHigh,
  battery_full: BatteryFull,
  send: PaperPlaneTilt,
  settings: GearSix,
  share: Export,
  reply: ArrowBendUpLeft,
  shield: ShieldCheck,
  storefront: Storefront,
  travel_explore: GlobeHemisphereWest,
  tune: SlidersHorizontal,
  verified: SealCheck,
  visibility: Eye,
  search: MagnifyingGlass,
};

// Keep semantic names and the existing layout wrapper stable across the app.
export function Icon({ name, size = 24, className = "" }: {
  name: string;
  size?: number;
  className?: string;
  /** Retained for older callers; Phosphor controls its own stroke weight. */
  strokeWidth?: number;
}) {
  const Glyph = ICONS[name] ?? Circle;
  return <span className={`icon ${className}`} style={{ width: size, height: size }} data-back-chevron={name === "arrow_back" ? "" : undefined} aria-hidden="true"><Glyph size={size} weight={name.endsWith("_filled") || name === "bookmark_added" ? "fill" : "bold"} /></span>;
}
