import { ArrowBendUpLeft as ArrowBendUpLeftGlyph } from "@phosphor-icons/react/dist/ssr/ArrowBendUpLeft";
import { ArrowLeft as ArrowLeftGlyph } from "@phosphor-icons/react/dist/ssr/ArrowLeft";
import { ArrowRight as ArrowRightGlyph } from "@phosphor-icons/react/dist/ssr/ArrowRight";
import { ArrowSquareOut as ArrowSquareOutGlyph } from "@phosphor-icons/react/dist/ssr/ArrowSquareOut";
import { ArrowUpRight as ArrowUpRightGlyph } from "@phosphor-icons/react/dist/ssr/ArrowUpRight";
import { At as AtGlyph } from "@phosphor-icons/react/dist/ssr/At";
import { BatteryFull as BatteryFullGlyph } from "@phosphor-icons/react/dist/ssr/BatteryFull";
import { Bell as BellGlyph } from "@phosphor-icons/react/dist/ssr/Bell";
import { BookmarkSimple as BookmarkSimpleGlyph } from "@phosphor-icons/react/dist/ssr/BookmarkSimple";
import { Calendar as CalendarGlyph } from "@phosphor-icons/react/dist/ssr/Calendar";
import { CalendarCheck as CalendarCheckGlyph } from "@phosphor-icons/react/dist/ssr/CalendarCheck";
import { CalendarDot as CalendarDotGlyph } from "@phosphor-icons/react/dist/ssr/CalendarDot";
import { CalendarDots as CalendarDotsGlyph } from "@phosphor-icons/react/dist/ssr/CalendarDots";
import { CaretDown as CaretDownGlyph } from "@phosphor-icons/react/dist/ssr/CaretDown";
import { CaretLeft as CaretLeftGlyph } from "@phosphor-icons/react/dist/ssr/CaretLeft";
import { CaretRight as CaretRightGlyph } from "@phosphor-icons/react/dist/ssr/CaretRight";
import { CaretUp as CaretUpGlyph } from "@phosphor-icons/react/dist/ssr/CaretUp";
import { CellSignalFull as CellSignalFullGlyph } from "@phosphor-icons/react/dist/ssr/CellSignalFull";
import { ChatCircle as ChatCircleGlyph } from "@phosphor-icons/react/dist/ssr/ChatCircle";
import { ChatCircleText as ChatCircleTextGlyph } from "@phosphor-icons/react/dist/ssr/ChatCircleText";
import { Chats as ChatsGlyph } from "@phosphor-icons/react/dist/ssr/Chats";
import { Check as CheckGlyph } from "@phosphor-icons/react/dist/ssr/Check";
import { CheckCircle as CheckCircleGlyph } from "@phosphor-icons/react/dist/ssr/CheckCircle";
import { Circle as CircleGlyph } from "@phosphor-icons/react/dist/ssr/Circle";
import { Clock as ClockGlyph } from "@phosphor-icons/react/dist/ssr/Clock";
import { Compass as CompassGlyph } from "@phosphor-icons/react/dist/ssr/Compass";
import { Copy as CopyGlyph } from "@phosphor-icons/react/dist/ssr/Copy";
import { CreditCard as CreditCardGlyph } from "@phosphor-icons/react/dist/ssr/CreditCard";
import { DeviceMobile as DeviceMobileGlyph } from "@phosphor-icons/react/dist/ssr/DeviceMobile";
import { DiceFive as DiceFiveGlyph } from "@phosphor-icons/react/dist/ssr/DiceFive";
import { DotsThree as DotsThreeGlyph } from "@phosphor-icons/react/dist/ssr/DotsThree";
import { Envelope as EnvelopeGlyph } from "@phosphor-icons/react/dist/ssr/Envelope";
import { Export as ExportGlyph } from "@phosphor-icons/react/dist/ssr/Export";
import { Eye as EyeGlyph } from "@phosphor-icons/react/dist/ssr/Eye";
import { Fingerprint as FingerprintGlyph } from "@phosphor-icons/react/dist/ssr/Fingerprint";
import { Flag as FlagGlyph } from "@phosphor-icons/react/dist/ssr/Flag";
import { GearSix as GearSixGlyph } from "@phosphor-icons/react/dist/ssr/GearSix";
import { Globe as GlobeGlyph } from "@phosphor-icons/react/dist/ssr/Globe";
import { GlobeHemisphereWest as GlobeHemisphereWestGlyph } from "@phosphor-icons/react/dist/ssr/GlobeHemisphereWest";
import { GridNine as GridNineGlyph } from "@phosphor-icons/react/dist/ssr/GridNine";
import { Heart as HeartGlyph } from "@phosphor-icons/react/dist/ssr/Heart";
import { House as HouseGlyph } from "@phosphor-icons/react/dist/ssr/House";
import { Image as ImageGlyph } from "@phosphor-icons/react/dist/ssr/Image";
import { Info as InfoGlyph } from "@phosphor-icons/react/dist/ssr/Info";
import { Lightning as LightningGlyph } from "@phosphor-icons/react/dist/ssr/Lightning";
import { Link as LinkGlyph } from "@phosphor-icons/react/dist/ssr/Link";
import { List as ListGlyph } from "@phosphor-icons/react/dist/ssr/List";
import { LockKey as LockKeyGlyph } from "@phosphor-icons/react/dist/ssr/LockKey";
import { MagnifyingGlass as MagnifyingGlassGlyph } from "@phosphor-icons/react/dist/ssr/MagnifyingGlass";
import { MapPin as MapPinGlyph } from "@phosphor-icons/react/dist/ssr/MapPin";
import { MapTrifold as MapTrifoldGlyph } from "@phosphor-icons/react/dist/ssr/MapTrifold";
import { Megaphone as MegaphoneGlyph } from "@phosphor-icons/react/dist/ssr/Megaphone";
import { Moon as MoonGlyph } from "@phosphor-icons/react/dist/ssr/Moon";
import { Palette as PaletteGlyph } from "@phosphor-icons/react/dist/ssr/Palette";
import { PaperPlaneTilt as PaperPlaneTiltGlyph } from "@phosphor-icons/react/dist/ssr/PaperPlaneTilt";
import { PencilSimple as PencilSimpleGlyph } from "@phosphor-icons/react/dist/ssr/PencilSimple";
import { Phone as PhoneGlyph } from "@phosphor-icons/react/dist/ssr/Phone";
import { Plus as PlusGlyph } from "@phosphor-icons/react/dist/ssr/Plus";
import { PlusCircle as PlusCircleGlyph } from "@phosphor-icons/react/dist/ssr/PlusCircle";
import { Pulse as PulseGlyph } from "@phosphor-icons/react/dist/ssr/Pulse";
import { QrCode as QrCodeGlyph } from "@phosphor-icons/react/dist/ssr/QrCode";
import { Rows as RowsGlyph } from "@phosphor-icons/react/dist/ssr/Rows";
import { SealCheck as SealCheckGlyph } from "@phosphor-icons/react/dist/ssr/SealCheck";
import { ShieldCheck as ShieldCheckGlyph } from "@phosphor-icons/react/dist/ssr/ShieldCheck";
import { SignOut as SignOutGlyph } from "@phosphor-icons/react/dist/ssr/SignOut";
import { SlidersHorizontal as SlidersHorizontalGlyph } from "@phosphor-icons/react/dist/ssr/SlidersHorizontal";
import { Sparkle as SparkleGlyph } from "@phosphor-icons/react/dist/ssr/Sparkle";
import { Star as StarGlyph } from "@phosphor-icons/react/dist/ssr/Star";
import { Storefront as StorefrontGlyph } from "@phosphor-icons/react/dist/ssr/Storefront";
import { Sun as SunGlyph } from "@phosphor-icons/react/dist/ssr/Sun";
import { TextT as TextTGlyph } from "@phosphor-icons/react/dist/ssr/TextT";
import { Trash as TrashGlyph } from "@phosphor-icons/react/dist/ssr/Trash";
import { User as UserGlyph } from "@phosphor-icons/react/dist/ssr/User";
import { UserCircle as UserCircleGlyph } from "@phosphor-icons/react/dist/ssr/UserCircle";
import { UserPlus as UserPlusGlyph } from "@phosphor-icons/react/dist/ssr/UserPlus";
import { Users as UsersGlyph } from "@phosphor-icons/react/dist/ssr/Users";
import { UsersThree as UsersThreeGlyph } from "@phosphor-icons/react/dist/ssr/UsersThree";
import { WifiHigh as WifiHighGlyph } from "@phosphor-icons/react/dist/ssr/WifiHigh";
import { X as XGlyph } from "@phosphor-icons/react/dist/ssr/X";
import type { Icon as PhosphorIcon, IconProps } from "@phosphor-icons/react";
import { forwardRef } from "react";

// All app glyphs use Fill; legacy stroke/fill props cannot override the family.
function filled(Glyph: PhosphorIcon) {
  return forwardRef<SVGSVGElement, IconProps>(function FilledIcon(
    { strokeWidth: _strokeWidth, fill: _fill, weight: _weight, ...props }, ref
  ) {
    return <Glyph ref={ref} {...props} weight="fill" />;
  });
}
export const Activity = filled(PulseGlyph);
export const ArrowBendUpLeft = filled(ArrowBendUpLeftGlyph);
export const ArrowLeft = filled(ArrowLeftGlyph);
export const ArrowRight = filled(ArrowRightGlyph);
export const ArrowSquareOut = filled(ArrowSquareOutGlyph);
export const ArrowUpRight = filled(ArrowUpRightGlyph);
export const At = filled(AtGlyph);
export const BatteryFull = filled(BatteryFullGlyph);
export const Bell = filled(BellGlyph);
export const Bookmark = filled(BookmarkSimpleGlyph);
export const BookmarkSimple = filled(BookmarkSimpleGlyph);
export const Calendar = filled(CalendarGlyph);
export const CalendarCheck = filled(CalendarCheckGlyph);
export const CalendarDays = filled(CalendarDotsGlyph);
export const CalendarDot = filled(CalendarDotGlyph);
export const CalendarDots = filled(CalendarDotsGlyph);
export const CaretDown = filled(CaretDownGlyph);
export const CaretLeft = filled(CaretLeftGlyph);
export const CaretRight = filled(CaretRightGlyph);
export const CaretUp = filled(CaretUpGlyph);
export const CellSignalFull = filled(CellSignalFullGlyph);
export const ChatCircle = filled(ChatCircleGlyph);
export const ChatCircleText = filled(ChatCircleTextGlyph);
export const Chats = filled(ChatsGlyph);
export const Check = filled(CheckGlyph);
export const CheckCircle = filled(CheckCircleGlyph);
export const ChevronDown = filled(CaretDownGlyph);
export const ChevronLeft = filled(CaretLeftGlyph);
export const ChevronRight = filled(CaretRightGlyph);
export const Circle = filled(CircleGlyph);
export const Clock = filled(ClockGlyph);
export const Compass = filled(CompassGlyph);
export const Copy = filled(CopyGlyph);
export const CreditCard = filled(CreditCardGlyph);
export const DeviceMobile = filled(DeviceMobileGlyph);
export const DiceFive = filled(DiceFiveGlyph);
export const DotsThree = filled(DotsThreeGlyph);
export const Envelope = filled(EnvelopeGlyph);
export const Export = filled(ExportGlyph);
export const Eye = filled(EyeGlyph);
export const Fingerprint = filled(FingerprintGlyph);
export const Flag = filled(FlagGlyph);
export const GearSix = filled(GearSixGlyph);
export const Globe = filled(GlobeGlyph);
export const GlobeHemisphereWest = filled(GlobeHemisphereWestGlyph);
export const GlobeLock = filled(GlobeHemisphereWestGlyph);
export const GridNine = filled(GridNineGlyph);
export const Heart = filled(HeartGlyph);
export const House = filled(HouseGlyph);
export const Image = filled(ImageGlyph);
export const Info = filled(InfoGlyph);
export const Lightning = filled(LightningGlyph);
export const Link = filled(LinkGlyph);
export const List = filled(ListGlyph);
export const LockKey = filled(LockKeyGlyph);
export const LockKeyhole = filled(LockKeyGlyph);
export const LogOut = filled(SignOutGlyph);
export const MagnifyingGlass = filled(MagnifyingGlassGlyph);
export const Map = filled(MapTrifoldGlyph);
export const MapPin = filled(MapPinGlyph);
export const MapTrifold = filled(MapTrifoldGlyph);
export const Megaphone = filled(MegaphoneGlyph);
export const MessageCircle = filled(ChatCircleGlyph);
export const Moon = filled(MoonGlyph);
export const Palette = filled(PaletteGlyph);
export const PaperPlaneTilt = filled(PaperPlaneTiltGlyph);
export const PencilSimple = filled(PencilSimpleGlyph);
export const Phone = filled(PhoneGlyph);
export const Plus = filled(PlusGlyph);
export const PlusCircle = filled(PlusCircleGlyph);
export const Pulse = filled(PulseGlyph);
export const QrCode = filled(QrCodeGlyph);
export const Rows = filled(RowsGlyph);
export const SealCheck = filled(SealCheckGlyph);
export const Search = filled(MagnifyingGlassGlyph);
export const Share2 = filled(ExportGlyph);
export const ShieldCheck = filled(ShieldCheckGlyph);
export const ShieldUser = filled(ShieldCheckGlyph);
export const SignOut = filled(SignOutGlyph);
export const SlidersHorizontal = filled(SlidersHorizontalGlyph);
export const Sparkle = filled(SparkleGlyph);
export const Sparkles = filled(SparkleGlyph);
export const Star = filled(StarGlyph);
export const Storefront = filled(StorefrontGlyph);
export const Sun = filled(SunGlyph);
export const TextT = filled(TextTGlyph);
export const Trash = filled(TrashGlyph);
export const User = filled(UserGlyph);
export const UserCircle = filled(UserCircleGlyph);
export const UserPlus = filled(UserPlusGlyph);
export const UserRound = filled(UserGlyph);
export const Users = filled(UsersThreeGlyph);
export const UsersThree = filled(UsersThreeGlyph);
export const WifiHigh = filled(WifiHighGlyph);
export const X = filled(XGlyph);
export const XIcon = filled(XGlyph);
