import { ArrowBendUpLeft as ArrowBendUpLeftGlyph } from "@phosphor-icons/react/dist/ssr/ArrowBendUpLeft";
import { ArrowLeft as ArrowLeftGlyph } from "@phosphor-icons/react/dist/ssr/ArrowLeft";
import { ArrowRight as ArrowRightGlyph } from "@phosphor-icons/react/dist/ssr/ArrowRight";
import { ArrowSquareOut as ArrowSquareOutGlyph } from "@phosphor-icons/react/dist/ssr/ArrowSquareOut";
import { ArrowUpRight as ArrowUpRightGlyph } from "@phosphor-icons/react/dist/ssr/ArrowUpRight";
import { At as AtGlyph } from "@phosphor-icons/react/dist/ssr/At";
import { BatteryFull as BatteryFullGlyph } from "@phosphor-icons/react/dist/ssr/BatteryFull";
import { Bell as BellGlyph } from "@phosphor-icons/react/dist/ssr/Bell";
import { BookmarkSimple as BookmarkSimpleGlyph } from "@phosphor-icons/react/dist/ssr/BookmarkSimple";
import { Calendar as CalendarGlyph } from "@phosphor-icons/react/dist/ssr/Calendar";
import { CalendarCheck as CalendarCheckGlyph } from "@phosphor-icons/react/dist/ssr/CalendarCheck";
import { CalendarDot as CalendarDotGlyph } from "@phosphor-icons/react/dist/ssr/CalendarDot";
import { CalendarDots as CalendarDotsGlyph } from "@phosphor-icons/react/dist/ssr/CalendarDots";
import { CaretDown as CaretDownGlyph } from "@phosphor-icons/react/dist/ssr/CaretDown";
import { CaretLeft as CaretLeftGlyph } from "@phosphor-icons/react/dist/ssr/CaretLeft";
import { CaretRight as CaretRightGlyph } from "@phosphor-icons/react/dist/ssr/CaretRight";
import { CaretUp as CaretUpGlyph } from "@phosphor-icons/react/dist/ssr/CaretUp";
import { CellSignalFull as CellSignalFullGlyph } from "@phosphor-icons/react/dist/ssr/CellSignalFull";
import { ChatCircle as ChatCircleGlyph } from "@phosphor-icons/react/dist/ssr/ChatCircle";
import { ChatCircleText as ChatCircleTextGlyph } from "@phosphor-icons/react/dist/ssr/ChatCircleText";
import { Chats as ChatsGlyph } from "@phosphor-icons/react/dist/ssr/Chats";
import { Check as CheckGlyph } from "@phosphor-icons/react/dist/ssr/Check";
import { CheckCircle as CheckCircleGlyph } from "@phosphor-icons/react/dist/ssr/CheckCircle";
import { Circle as CircleGlyph } from "@phosphor-icons/react/dist/ssr/Circle";
import { Clock as ClockGlyph } from "@phosphor-icons/react/dist/ssr/Clock";
import { Compass as CompassGlyph } from "@phosphor-icons/react/dist/ssr/Compass";
import { Copy as CopyGlyph } from "@phosphor-icons/react/dist/ssr/Copy";
import { CreditCard as CreditCardGlyph } from "@phosphor-icons/react/dist/ssr/CreditCard";
import { DeviceMobile as DeviceMobileGlyph } from "@phosphor-icons/react/dist/ssr/DeviceMobile";
import { DiceFive as DiceFiveGlyph } from "@phosphor-icons/react/dist/ssr/DiceFive";
import { DotsThree as DotsThreeGlyph } from "@phosphor-icons/react/dist/ssr/DotsThree";
import { Envelope as EnvelopeGlyph } from "@phosphor-icons/react/dist/ssr/Envelope";
import { Export as ExportGlyph } from "@phosphor-icons/react/dist/ssr/Export";
import { Eye as EyeGlyph } from "@phosphor-icons/react/dist/ssr/Eye";
import { Fingerprint as FingerprintGlyph } from "@phosphor-icons/react/dist/ssr/Fingerprint";
import { Flag as FlagGlyph } from "@phosphor-icons/react/dist/ssr/Flag";
import { GearSix as GearSixGlyph } from "@phosphor-icons/react/dist/ssr/GearSix";
import { Globe as GlobeGlyph } from "@phosphor-icons/react/dist/ssr/Globe";
import { GlobeHemisphereWest as GlobeHemisphereWestGlyph } from "@phosphor-icons/react/dist/ssr/GlobeHemisphereWest";
import { GridNine as GridNineGlyph } from "@phosphor-icons/react/dist/ssr/GridNine";
import { Heart as HeartGlyph } from "@phosphor-icons/react/dist/ssr/Heart";
import { House as HouseGlyph } from "@phosphor-icons/react/dist/ssr/House";
import { Image as ImageGlyph } from "@phosphor-icons/react/dist/ssr/Image";
import { Info as InfoGlyph } from "@phosphor-icons/react/dist/ssr/Info";
import { Lightning as LightningGlyph } from "@phosphor-icons/react/dist/ssr/Lightning";
import { Link as LinkGlyph } from "@phosphor-icons/react/dist/ssr/Link";
import { List as ListGlyph } from "@phosphor-icons/react/dist/ssr/List";
import { LockKey as LockKeyGlyph } from "@phosphor-icons/react/dist/ssr/LockKey";
import { MagnifyingGlass as MagnifyingGlassGlyph } from "@phosphor-icons/react/dist/ssr/MagnifyingGlass";
import { MapPin as MapPinGlyph } from "@phosphor-icons/react/dist/ssr/MapPin";
import { MapTrifold as MapTrifoldGlyph } from "@phosphor-icons/react/dist/ssr/MapTrifold";
import { Megaphone as MegaphoneGlyph } from "@phosphor-icons/react/dist/ssr/Megaphone";
import { Moon as MoonGlyph } from "@phosphor-icons/react/dist/ssr/Moon";
import { Palette as PaletteGlyph } from "@phosphor-icons/react/dist/ssr/Palette";
import { PaperPlaneTilt as PaperPlaneTiltGlyph } from "@phosphor-icons/react/dist/ssr/PaperPlaneTilt";
import { PencilSimple as PencilSimpleGlyph } from "@phosphor-icons/react/dist/ssr/PencilSimple";
import { Phone as PhoneGlyph } from "@phosphor-icons/react/dist/ssr/Phone";
import { Plus as PlusGlyph } from "@phosphor-icons/react/dist/ssr/Plus";
import { PlusCircle as PlusCircleGlyph } from "@phosphor-icons/react/dist/ssr/PlusCircle";
import { Pulse as PulseGlyph } from "@phosphor-icons/react/dist/ssr/Pulse";
import { QrCode as QrCodeGlyph } from "@phosphor-icons/react/dist/ssr/QrCode";
import { Rows as RowsGlyph } from "@phosphor-icons/react/dist/ssr/Rows";
import { SealCheck as SealCheckGlyph } from "@phosphor-icons/react/dist/ssr/SealCheck";
import { ShieldCheck as ShieldCheckGlyph } from "@phosphor-icons/react/dist/ssr/ShieldCheck";
import { SignOut as SignOutGlyph } from "@phosphor-icons/react/dist/ssr/SignOut";
import { SlidersHorizontal as SlidersHorizontalGlyph } from "@phosphor-icons/react/dist/ssr/SlidersHorizontal";
import { Sparkle as SparkleGlyph } from "@phosphor-icons/react/dist/ssr/Sparkle";
import { Star as StarGlyph } from "@phosphor-icons/react/dist/ssr/Star";
import { Storefront as StorefrontGlyph } from "@phosphor-icons/react/dist/ssr/Storefront";
import { Sun as SunGlyph } from "@phosphor-icons/react/dist/ssr/Sun";
import { TextT as TextTGlyph } from "@phosphor-icons/react/dist/ssr/TextT";
import { Trash as TrashGlyph } from "@phosphor-icons/react/dist/ssr/Trash";
import { User as UserGlyph } from "@phosphor-icons/react/dist/ssr/User";
import { UserCircle as UserCircleGlyph } from "@phosphor-icons/react/dist/ssr/UserCircle";
import { UserPlus as UserPlusGlyph } from "@phosphor-icons/react/dist/ssr/UserPlus";
import { Users as UsersGlyph } from "@phosphor-icons/react/dist/ssr/Users";
import { UsersThree as UsersThreeGlyph } from "@phosphor-icons/react/dist/ssr/UsersThree";
import { WifiHigh as WifiHighGlyph } from "@phosphor-icons/react/dist/ssr/WifiHigh";
import { X as XGlyph } from "@phosphor-icons/react/dist/ssr/X";
import type { Icon as PhosphorIcon, IconProps } from "@phosphor-icons/react";
import { forwardRef } from "react";

// Outline by default; selected controls can explicitly request Fill.
function appIcon(Glyph: PhosphorIcon) {
  return forwardRef<SVGSVGElement, IconProps>(function AppIcon(
    { strokeWidth: _strokeWidth, fill: _fill, weight = "regular", ...props }, ref
  ) {
    return <Glyph ref={ref} {...props} weight={weight} />;
  });
}
export const Activity = appIcon(PulseGlyph);
export const ArrowBendUpLeft = appIcon(ArrowBendUpLeftGlyph);
export const ArrowLeft = appIcon(ArrowLeftGlyph);
export const ArrowRight = appIcon(ArrowRightGlyph);
export const ArrowSquareOut = appIcon(ArrowSquareOutGlyph);
export const ArrowUpRight = appIcon(ArrowUpRightGlyph);
export const At = appIcon(AtGlyph);
export const BatteryFull = appIcon(BatteryFullGlyph);
export const Bell = appIcon(BellGlyph);
export const Bookmark = appIcon(BookmarkSimpleGlyph);
export const BookmarkSimple = appIcon(BookmarkSimpleGlyph);
export const Calendar = appIcon(CalendarGlyph);
export const CalendarCheck = appIcon(CalendarCheckGlyph);
export const CalendarDays = appIcon(CalendarDotsGlyph);
export const CalendarDot = appIcon(CalendarDotGlyph);
export const CalendarDots = appIcon(CalendarDotsGlyph);
export const CaretDown = appIcon(CaretDownGlyph);
export const CaretLeft = appIcon(CaretLeftGlyph);
export const CaretRight = appIcon(CaretRightGlyph);
export const CaretUp = appIcon(CaretUpGlyph);
export const CellSignalFull = appIcon(CellSignalFullGlyph);
export const ChatCircle = appIcon(ChatCircleGlyph);
export const ChatCircleText = appIcon(ChatCircleTextGlyph);
export const Chats = appIcon(ChatsGlyph);
export const Check = appIcon(CheckGlyph);
export const CheckCircle = appIcon(CheckCircleGlyph);
export const ChevronDown = appIcon(CaretDownGlyph);
export const ChevronLeft = appIcon(CaretLeftGlyph);
export const ChevronRight = appIcon(CaretRightGlyph);
export const Circle = appIcon(CircleGlyph);
export const Clock = appIcon(ClockGlyph);
export const Compass = appIcon(CompassGlyph);
export const Copy = appIcon(CopyGlyph);
export const CreditCard = appIcon(CreditCardGlyph);
export const DeviceMobile = appIcon(DeviceMobileGlyph);
export const DiceFive = appIcon(DiceFiveGlyph);
export const DotsThree = appIcon(DotsThreeGlyph);
export const Envelope = appIcon(EnvelopeGlyph);
export const Export = appIcon(ExportGlyph);
export const Eye = appIcon(EyeGlyph);
export const Fingerprint = appIcon(FingerprintGlyph);
export const Flag = appIcon(FlagGlyph);
export const GearSix = appIcon(GearSixGlyph);
export const Globe = appIcon(GlobeGlyph);
export const GlobeHemisphereWest = appIcon(GlobeHemisphereWestGlyph);
export const GlobeLock = appIcon(GlobeHemisphereWestGlyph);
export const GridNine = appIcon(GridNineGlyph);
export const Heart = appIcon(HeartGlyph);
export const House = appIcon(HouseGlyph);
export const Image = appIcon(ImageGlyph);
export const Info = appIcon(InfoGlyph);
export const Lightning = appIcon(LightningGlyph);
export const Link = appIcon(LinkGlyph);
export const List = appIcon(ListGlyph);
export const LockKey = appIcon(LockKeyGlyph);
export const LockKeyhole = appIcon(LockKeyGlyph);
export const LogOut = appIcon(SignOutGlyph);
export const MagnifyingGlass = appIcon(MagnifyingGlassGlyph);
export const Map = appIcon(MapTrifoldGlyph);
export const MapPin = appIcon(MapPinGlyph);
export const MapTrifold = appIcon(MapTrifoldGlyph);
export const Megaphone = appIcon(MegaphoneGlyph);
export const MessageCircle = appIcon(ChatCircleGlyph);
export const Moon = appIcon(MoonGlyph);
export const Palette = appIcon(PaletteGlyph);
export const PaperPlaneTilt = appIcon(PaperPlaneTiltGlyph);
export const PencilSimple = appIcon(PencilSimpleGlyph);
export const Phone = appIcon(PhoneGlyph);
export const Plus = appIcon(PlusGlyph);
export const PlusCircle = appIcon(PlusCircleGlyph);
export const Pulse = appIcon(PulseGlyph);
export const QrCode = appIcon(QrCodeGlyph);
export const Rows = appIcon(RowsGlyph);
export const SealCheck = appIcon(SealCheckGlyph);
export const Search = appIcon(MagnifyingGlassGlyph);
export const Share2 = appIcon(ExportGlyph);
export const ShieldCheck = appIcon(ShieldCheckGlyph);
export const ShieldUser = appIcon(ShieldCheckGlyph);
export const SignOut = appIcon(SignOutGlyph);
export const SlidersHorizontal = appIcon(SlidersHorizontalGlyph);
export const Sparkle = appIcon(SparkleGlyph);
export const Sparkles = appIcon(SparkleGlyph);
export const Star = appIcon(StarGlyph);
export const Storefront = appIcon(StorefrontGlyph);
export const Sun = appIcon(SunGlyph);
export const TextT = appIcon(TextTGlyph);
export const Trash = appIcon(TrashGlyph);
export const User = appIcon(UserGlyph);
export const UserCircle = appIcon(UserCircleGlyph);
export const UserPlus = appIcon(UserPlusGlyph);
export const UserRound = appIcon(UserGlyph);
export const Users = appIcon(UsersThreeGlyph);
export const UsersThree = appIcon(UsersThreeGlyph);
export const WifiHigh = appIcon(WifiHighGlyph);
export const X = appIcon(XGlyph);
export const XIcon = appIcon(XGlyph);
