import assert from 'node:assert/strict';
import { AsyncLocalStorage } from 'node:async_hooks';
import { createRequire } from 'node:module';
import { mkdtempSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { randomBytes, createHash } from 'node:crypto';
import { SignJWT } from 'jose';
import { and, eq } from 'drizzle-orm';

async function main() {
  if(process.env.DATABASE_URL || process.env.VERCEL)throw Error('Event tests require an isolated database');
  process.env.PGLITE_DATA_DIR=join(mkdtempSync(join(tmpdir(),'fittlist-event-check-')),'db');
  process.env.SESSION_SECRET=randomBytes(32).toString('hex');process.env.ADMIN_EMAILS='';process.env.INVITE_ONLY='false';
  const request=new AsyncLocalStorage<Map<string,string>>(), require=createRequire(import.meta.url);
  const runtime=require('node:module'), original=runtime._load.bind(runtime);
  runtime._load=(id:string,...args:unknown[])=>id==='server-only'?{}:original(id,...args);
  require('next/headers').cookies=async()=>({get:(key:string)=>request.getStore()?.has(key)?{value:request.getStore()!.get(key)}:undefined,set:(key:string,value:string)=>request.getStore()?.set(key,value),delete:(key:string)=>request.getStore()?.delete(key)});
  require('next/headers').headers=async()=>new Headers();
  require('next/cache').revalidatePath=()=>{};require('next/server').after=()=>{};
  globalThis.fetch=async()=>{throw Error('External network disabled');};
  const {getDb,schema}=await import('../src/db');
  const {writeAttendance,validateRegistrationIntent,csvCell}=await import('../src/lib/event-registration');
  const {eventRoster,eventSchedule}=await import('../src/lib/event-data');
  const {saveEventSettings,checkInEvent,registerForEvent}=await import('../src/app/actions/event-registration');
  const {consumeMagicToken}=await import('../src/app/actions/auth');
  const {setGoing}=await import('../src/app/actions/going');
  const db=await getDb();
  const people=await db.insert(schema.users).values(Array.from({length:8},(_,i)=>({email:`event-${i}@example.test`,name:`Event ${i}`,handle:`event${i}`,kind:i===0?'gym':'fan',onboardedAt:new Date()}))).returning();
  const [studio,other]=await db.insert(schema.studios).values([{name:'Test Expo',slug:'test-expo',address:'Test hall',accountUserId:people[0].id,registrationDate:'2099-09-12'},{name:'Other Expo',slug:'other-expo',address:'Other hall'}]).returning();
  await db.insert(schema.studioManagers).values({studioId:studio.id,userId:people[1].id});
  const date='2099-09-12',dow=(new Date(date+'T12:00:00Z').getUTCDay()+6)%7;
  const [cls,second]=await db.insert(schema.classes).values([{userId:people[0].id,studioId:studio.id,name:'Expo Strength',dayOfWeek:dow,specificDate:date,startTime:'10:00',durationMin:45,isPublic:true,rsvp:true,registrationCapacity:2},{userId:people[0].id,studioId:studio.id,name:'Expo Yoga',dayOfWeek:dow,specificDate:date,startTime:'11:00',durationMin:45,isPublic:true,rsvp:true,registrationCapacity:20}]).returning();
  async function as<T>(i:number,fn:()=>Promise<T>){const token=await new SignJWT({uid:people[i].id,sv:0}).setProtectedHeader({alg:'HS256'}).setExpirationTime('1h').sign(new TextEncoder().encode(process.env.SESSION_SECRET));return request.run(new Map([['fl_session',token]]),fn);}
  const intent={studioId:studio.id,classId:cls.id,date,name:'Taylor Reed'};
  assert(await validateRegistrationIntent(intent));assert.equal(await validateRegistrationIntent({...intent,studioId:other.id}),null);assert.equal(await validateRegistrationIntent({...intent,date:'2099-02-31'}),null);
  const attempts=await Promise.all([2,3,4].map(i=>writeAttendance(people[i].id,cls.id,date,true,studio.id)));
  assert.equal(attempts.filter(r=>r.ok).length,2,'Concurrent registrations cannot exceed capacity');
  const entries=await db.select().from(schema.attendances).where(eq(schema.attendances.classId,cls.id));assert.equal(entries.length,2);assert(entries.every(r=>!r.isPublic));
  const winner=people.findIndex(p=>p.id===entries[0].userId),loser=[2,3,4].find(i=>!entries.some(e=>e.userId===people[i].id))!;
  assert((await as(winner,()=>setGoing(cls.id,date,true))).ok,'Repeat registration is idempotent');
  assert(!(await as(loser,()=>setGoing(cls.id,date,true))).ok,'Ordinary save cannot bypass capacity');
  assert.equal(await as(2,()=>eventRoster(studio.slug!)),null,'Attendee cannot read email roster');
  assert.equal(await request.run(new Map(),()=>eventRoster(studio.slug!)),null,'Anonymous cannot read roster');
  assert(!(await as(2,()=>checkInEvent(studio.slug!,entries[0].id,true))).ok);
  assert(!(await as(2,()=>saveEventSettings(studio.slug!,date,[{id:cls.id,capacity:10}]))).ok);
  assert(!(await as(1,()=>saveEventSettings(studio.slug!,date,[{id:cls.id,capacity:1}]))).ok,'Cannot shrink below current tally');
  assert((await as(1,()=>checkInEvent(studio.slug!,entries[0].id,true))).ok);
  assert((await as(1,()=>eventRoster(studio.slug!)))?.find(r=>r.id===entries[0].id)?.checkedInAt);
  assert((await as(1,()=>checkInEvent(studio.slug!,entries[0].id,false))).ok);
  assert(!(await as(1,()=>checkInEvent(other.slug!,entries[0].id,true))).ok);
  assert((await as(winner,()=>registerForEvent(studio.slug!,cls.id,date,false))).ok);
  assert((await as(loser,()=>registerForEvent(studio.slug!,cls.id,date,true))).ok,'Cancellation frees capacity');
  await as(loser,()=>registerForEvent(studio.slug!,second.id,date,true));
  const totals=await as(1,()=>eventSchedule(studio.slug!,true));assert.equal(totals?.uniqueAttendees,2);assert.equal(totals?.classes.reduce((n,c)=>n+c.count,0),3);
  const token=randomBytes(32).toString('hex');
  await db.insert(schema.magicLinks).values({email:'new-expo@example.test',tokenHash:createHash('sha256').update(token).digest('hex'),purpose:'signup',registration:{...intent,classId:second.id},expiresAt:new Date(Date.now()+60000)});
  const result=await request.run(new Map(),()=>consumeMagicToken(token));
  assert.match(result?.registrationHref || '',/\/s\/test-expo\/register\?class=/,'Fresh browser returns to selected class');
  const [newUser]=await db.select().from(schema.users).where(eq(schema.users.email,'new-expo@example.test'));
  assert.equal(newUser.name,'Taylor Reed');assert(newUser.handle && newUser.onboardedAt);assert.equal(newUser.discoverable,false);
  const [confirmed]=await db.select().from(schema.attendances).where(and(eq(schema.attendances.userId,newUser.id),eq(schema.attendances.classId,second.id)));assert(confirmed);assert.equal(confirmed.isPublic,false);
  assert.equal(await request.run(new Map(),()=>consumeMagicToken(token)),null,'Email token cannot register twice');
  assert.match(csvCell('=HYPERLINK("bad")'),/^"'/,'CSV neutralizes formulas');
  await db.insert(schema.studioClosedDays).values({studioId:studio.id,occurrenceDate:date});
  assert(!(await writeAttendance(people[7].id,second.id,date,true,studio.id)).ok,'Closure stops signup');
  console.log('PASS event capacity races, idempotency, cancellation, roster isolation, admin checks, unique tally, email continuation, minimal profile, token replay, CSV safety and closed dates');
}
main().then(()=>process.exit(0)).catch(e=>{console.error(e.message);process.exit(1);});
