"use client";
import { BackButton } from "@/components/BackButton";
import { useEffect, useState } from "react";
import { ChevronRight, Plus } from "@/components/PhosphorIcons";
import { usePrototype, dateLabel, timeLabel } from "./prototype-state";
import { loadPreviewStudio } from "./studio-data";
import styles from "./preview.module.css";
type Slot={id:string;date:string;name:string;time:string;duration:number;coach:string;published:boolean};
export type StudioDraft={website?:string;phone?:string;contactEmail?:string;instagram?:string;slots:Slot[];staff:{id:string;name:string;photo:string|null;roles:string}[];requests:{id:string;className:string;iso:string;fromName:string|null;toName:string;kind:string}[];closed:string[];standard:Slot[];about:string;approval:boolean;showCoaches:boolean;decisions:Record<string,string>};
const sections=[['Calendar','Schedule classes, assign coaches, and manage open shifts'],['Requests','Review pickup and transfer requests'],['Staff','Your teaching team and working roles'],['Standard week','Build a reusable weekly schedule'],['Class counts','Teaching totals and CSV export'],['Profile & settings','Studio description, visibility, and approvals']];
export default function StudioWorkspace({name,view}:{name:string;view:string}) {
 const p=usePrototype();const d=p.studioDrafts[name];const [error,setError]=useState("");const [filter,setFilter]=useState("all");const [selected,setSelected]=useState<Slot|null>(null);const [newStaff,setNewStaff]=useState("");const [message,setMessage]=useState("");
 const open=(next:string)=>p.open({kind:"manage",name,view:next});
 const put=(next:StudioDraft)=>p.setStudioDrafts(v=>({...v,[name]:next}));
 useEffect(()=>{if(d)return;let active=true;
 const load=async()=>{try{
 let data:StudioDraft;
 if(p.live){const live=await loadPreviewStudio(name);data={slots:live.week?.days.flatMap(day=>day.items.map(c=>({id:`${c.id}.${day.iso}`,date:day.iso,name:c.name,time:c.startTime,duration:c.durationMin,coach:c.onName||"",published:c.isPublic})))||[],staff:live.staff,requests:live.requests,closed:live.week?.days.filter(day=>day.closed).map(day=>day.iso)||[],standard:[],about:p.live?.studios.find(s=>s.name===name)?.about||"",website:p.live?.studios.find(s=>s.name===name)?.website||"",phone:p.live?.studios.find(s=>s.name===name)?.phone||"",contactEmail:p.live?.studios.find(s=>s.name===name)?.contactEmail||"",instagram:p.live?.studios.find(s=>s.name===name)?.instagram||"",approval:true,showCoaches:true,decisions:{}};}
 else {const slots=p.schedule.filter(c=>c.place===name).map(c=>({id:c.id,date:c.date,name:c.name,time:c.time,duration:Number(c.duration),coach:c.coach,published:true}));const date=slots[0]?.date||new Date().toISOString().slice(0,10);data={slots:[...slots,{id:"demo-open",date,name:"Strength circuit",time:"12:00",duration:45,coach:"",published:false}],staff:[{id:"me",name:p.profile.name,photo:p.profile.photo,roles:"owner · coach"},{id:"erin",name:"Erin Clyne",photo:null,roles:"coach"},{id:"freddie",name:"Freddie Morgan",photo:null,roles:"coach"}],requests:[{id:"demo-request",className:slots[0]?.name||"Strength circuit",iso:date,fromName:p.profile.name,toName:"Erin Clyne",kind:"transfer"}],closed:[],standard:[],about:"",website:"",phone:"",contactEmail:"",instagram:"",approval:true,showCoaches:true,decisions:{}};}
 if(active)put(data);
 }catch{if(active)setError("Couldn’t load studio management. Go back and try again.");}};void load();return()=>{active=false;};
 // Keep drafts across detail navigation; never overwrite local edits.
 // eslint-disable-next-line react-hooks/exhaustive-deps
 },[name,!!d]);
 if(!d)return <><BackButton className={styles.backButton} onClick={p.back}/><h1 className={styles.pageTitle}>{name}</h1><p role="status">{error||"Loading studio management…"}</p></>;
 const update=(change:Partial<StudioDraft>)=>put({...d,...change});
 const activeSlots=d.slots.filter(s=>!d.closed.includes(s.date));const openSlots=activeSlots.filter(s=>!s.coach);const pending=d.requests.filter(r=>!d.decisions[r.id]);
 const dates=[...new Set(d.slots.map(s=>s.date))].sort();
 const saveSlot=()=>{if(!selected?.name.trim())return;update({slots:d.slots.some(s=>s.id===selected.id)?d.slots.map(s=>s.id===selected.id?selected:s):[...d.slots,selected]});setSelected(null);setMessage("Class updated in this preview.");};
 const download=()=>{const rows=[['Coach','Classes','Minutes'],...d.staff.map(person=>{const slots=activeSlots.filter(s=>s.coach===person.name);return [person.name,String(slots.length),String(slots.reduce((n,s)=>n+s.duration,0))];})];const csv=rows.map(row=>row.map(value=>'"'+(/^[=+@\-]/.test(value)?"'":"")+value.replaceAll('"','""')+'"').join(',')).join('\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));const a=document.createElement('a');a.href=url;a.download='studio-class-counts.csv';a.click();URL.revokeObjectURL(url);};
 return <div className={styles.studioWorkspace}>
 <BackButton className={styles.backButton} onClick={p.back}/><p className={styles.sectionIntro}>{name}</p><h1 className={styles.pageTitle}>{view}</h1>
 <p className={styles.prototypeNote}>{p.live&&"Account schedule and staff · "}Changes stay in this preview. No invitations or notifications are sent.</p>
 {view==="Dashboard"&&<><div className={styles.metricGrid}>{[["Classes",activeSlots.length,"Calendar"],["Open shifts",openSlots.length,"Calendar"],["Staff",d.staff.length,"Staff"],["Requests",pending.length,"Requests"]].map(([label,count,target])=><button key={label} onClick={()=>{setFilter(label==="Open shifts"?"open":"all");open(String(target));}}><strong>{count}</strong><span>{label}</span></button>)}</div><section className={styles.studioPanel}><h2>Coach coverage</h2><strong>{activeSlots.length?Math.round((activeSlots.length-openSlots.length)/activeSlots.length*100):0}% assigned</strong><progress aria-label="Assigned classes" value={activeSlots.length-openSlots.length} max={activeSlots.length||1}/><p>{openSlots.length} classes need a coach in the loaded schedule.</p></section><div className={styles.stack}>{sections.map(([title,detail])=><button key={title} className={styles.studioLink} onClick={()=>open(title)}><span><strong>{title}</strong><small>{detail}</small></span><ChevronRight size={18}/></button>)}<button className={styles.studioLink} onClick={()=>p.open({kind:"studio",name})}>View studio profile<ChevronRight size={18}/></button></div></>}
 {view==="Calendar"&&<>{selected?<form className={styles.detailForm} onSubmit={e=>{e.preventDefault();saveSlot();}}><h2>{d.slots.some(s=>s.id===selected.id)?"Edit class":"Add class"}</h2><label>Class name<input required value={selected.name} onChange={e=>setSelected({...selected,name:e.target.value})}/></label><label>Date<input required type="date" value={selected.date} onChange={e=>setSelected({...selected,date:e.target.value})}/></label><label>Start time<input required type="time" value={selected.time} onChange={e=>setSelected({...selected,time:e.target.value})}/></label><label>Duration in minutes<input required type="number" min="5" max="480" value={selected.duration} onChange={e=>setSelected({...selected,duration:Number(e.target.value)})}/></label><label>Assigned coach<select value={selected.coach} onChange={e=>setSelected({...selected,coach:e.target.value})}><option value="">Open shift</option>{d.staff.map(person=><option key={person.id}>{person.name}</option>)}</select></label><label><input type="checkbox" checked={selected.published} onChange={e=>setSelected({...selected,published:e.target.checked})}/> Publish on studio calendar</label><button className={styles.studioPrimary}>Save class</button><button type="button" className={styles.profileProLink} onClick={()=>setSelected(null)}>Cancel</button></form>:<><div className={styles.profileActions}><button className={styles.profileProLink} onClick={()=>setSelected({id:`draft-${Date.now()}`,date:dates[0]||new Date().toISOString().slice(0,10),name:"",time:"09:00",duration:60,coach:"",published:false})}><Plus size={18}/>Add class</button><select aria-label="Schedule filter" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All classes</option><option value="open">Open shifts</option><option value="draft">Drafts</option></select></div>{dates.map(date=><section key={date} className={styles.studioDay}><div className={styles.sectionTitle}><h2>{dateLabel(date)}</h2><button className={styles.profileProLink} onClick={()=>update({closed:d.closed.includes(date)?d.closed.filter(x=>x!==date):[...d.closed,date]})}>{d.closed.includes(date)?"Reopen day":"Close day"}</button></div>{d.closed.includes(date)?<p>Studio closed. Classes are retained.</p>:<div className={styles.stack}>{d.slots.filter(s=>s.date===date&&(filter==="all"||filter==="open"&&!s.coach||filter==="draft"&&!s.published)).map(s=><button className={styles.studioLink} key={s.id} onClick={()=>setSelected({...s})}><span><small>{timeLabel(s.time)} · {s.duration} min · {s.published?"Published":"Draft"}</small><strong>{s.name}</strong><small>{s.coach||"Open shift"}</small></span><ChevronRight size={18}/></button>)}</div>}</section>)}{!dates.length&&<p>No classes in the loaded week. Add a class to start.</p>}</>}</>}
 {view==="Requests"&&<div className={styles.stack}>{pending.length?pending.map(r=><section className={styles.studioPanel} key={r.id}><h2>{r.className}</h2><p>{dateLabel(r.iso)} · {r.fromName||"Open shift"} → {r.toName}</p><p>{r.kind==="pickup"?"Pickup request":"Transfer request"}</p><div className={styles.profileActions}><button className={styles.profileProLink} onClick={()=>update({decisions:{...d.decisions,[r.id]:"approved"},slots:d.slots.map(s=>s.name===r.className&&s.date===r.iso?{...s,coach:r.toName}:s)})}>Approve in preview</button><button className={styles.profileProLink} onClick={()=>update({decisions:{...d.decisions,[r.id]:"declined"}})}>Decline</button></div></section>):<p>No pending requests.</p>}</div>}
 {view==="Staff"&&<><div className={styles.stack}>{d.staff.map(person=><div className={styles.studioPanel} key={person.id}><strong>{person.name}</strong><p>{person.roles}</p><p>{activeSlots.filter(s=>s.coach===person.name).length} assigned classes</p></div>)}</div><h2 className={styles.planHeading}>Add staff</h2><form className={styles.detailForm} onSubmit={e=>{e.preventDefault();if(!newStaff.trim())return;update({staff:[...d.staff,{id:`staff-${Date.now()}`,name:newStaff.trim(),photo:null,roles:"coach"}]});setNewStaff("");setMessage("Staff added locally. No invitation sent.");}}><label>Name<input required value={newStaff} onChange={e=>setNewStaff(e.target.value)}/></label><button className={styles.studioPrimary}>Add to preview team</button></form></>}
 {view==="Standard week"&&<><p className={styles.sectionIntro}>Try a reusable schedule using the classes currently loaded. This preview does not change standing classes on main.</p><button className={styles.profileProLink} onClick={()=>{update({standard:d.slots.map(s=>({...s}))});setMessage("Loaded schedule saved as a local template.");}}>Use loaded schedule as template</button><div className={styles.stack}>{d.standard.map(s=><div className={styles.studioPanel} key={s.id}><strong>{s.name}</strong><p>{dateLabel(s.date)} · {timeLabel(s.time)}</p></div>)}</div>{d.standard.length>0&&<button className={styles.studioPrimary} onClick={()=>{const shifted=d.standard.map(s=>{const date=new Date(`${s.date}T12:00:00Z`);date.setUTCDate(date.getUTCDate()+7);return {...s,id:`template-${s.id}`,date:date.toISOString().slice(0,10),published:false};});update({slots:[...d.slots,...shifted.filter(s=>!d.slots.some(c=>c.id===s.id))]});setMessage("Next week added as drafts. Review them in Calendar.");}}>Apply to next week as drafts</button>}</>}
 {view==="Class counts"&&<><p className={styles.sectionIntro}>Loaded schedule only. Closed days excluded.</p><div className={styles.stack}>{d.staff.map(person=>{const slots=activeSlots.filter(s=>s.coach===person.name);return <div className={styles.studioPanel} key={person.id}><strong>{person.name}</strong><p>{slots.length} classes · {slots.reduce((sum,s)=>sum+s.duration,0)} minutes</p></div>;})}</div><button className={styles.studioPrimary} onClick={download}>Download CSV</button></>}
 {view==="Profile & settings"&&<form className={styles.detailForm} onSubmit={e=>{e.preventDefault();setMessage("Settings kept in this preview.");}}><label>Studio description<textarea value={d.about} onChange={e=>update({about:e.target.value})}/></label>{([["website","Website"],["phone","Phone"],["contactEmail","Public email"],["instagram","Instagram"]] as const).map(([key,label])=><label key={key}>{label}<input value={d[key]||""} onChange={e=>update({[key]:e.target.value})}/></label>)}<label><input type="checkbox" checked={d.approval} onChange={e=>update({approval:e.target.checked})}/> Require approval for shift changes</label><label><input type="checkbox" checked={d.showCoaches} onChange={e=>update({showCoaches:e.target.checked})}/> Show coaches on the public profile</label><p>These settings are local design examples, not your saved studio settings.</p><button className={styles.studioPrimary}>Save settings in preview</button></form>}
 <p role="status">{message}</p>
 </div>;
}
